# Generated by Django 2.2.3 on 2020-03-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citizen_complaint_processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=100)),
                ('email_id', models.EmailField(error_messages={'blank': 'This field cannot be left blank', 'invalid': 'This is an invalid email ID'}, max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
