# Generated by Django 2.2.3 on 2020-03-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citizen_complaint_processing', '0002_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='email_id',
            field=models.EmailField(error_messages={'blank': 'This field cannot be left blank', 'invalid': 'This is an invalid email ID'}, max_length=50, unique=True),
        ),
    ]
