# Generated by Django 2.2.3 on 2020-03-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citizen_complaint_processing', '0003_auto_20200316_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
